# Generated by Django 3.0.6 on 2020-06-04 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jilid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jilid', models.CharField(max_length=50)),
                ('harga_jilid', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pengambilan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempat_pengambilan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_print', models.CharField(max_length=50)),
                ('harga', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Belum Di Cetak', 'belum_di_cetak'), ('Sudah Di Cetak', 'sudah_di_cetak')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jilid', models.CharField(default='Ya', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('waktu_pengambilan', models.DateField()),
                ('copy', models.IntegerField(default=1)),
                ('harga_bayar', models.FloatField(default=0)),
                ('status_bayar', models.CharField(choices=[('Telah Dibayar', 'dibayar'), ('Menunggu Pembayaran', 'menunggu'), ('Belum Dibayar', 'belum')], default='Belum Dibayar', max_length=255)),
                ('bukti', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('pengambilan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pengambilan')),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('print_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Print')),
                ('status_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.Status')),
            ],
        ),
        migrations.CreateModel(
            name='FilePemesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('nama_file', models.CharField(blank=True, max_length=255, null=True)),
                ('banyak_halaman', models.IntegerField(blank=True, default=0, null=True)),
                ('harga', models.FloatField(default=0)),
                ('pemesanan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pemesanan')),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bukti', models.ImageField(upload_to='documents/')),
                ('status_bayar', models.CharField(choices=[('Telah Dibayar', 'dibayar'), ('Menunggu Pembayaran', 'menunggu')], default='Menunggu Pembayaran', max_length=255)),
                ('pemesanan_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Pemesanan')),
            ],
        ),
    ]
