# Generated by Django 3.0.6 on 2020-06-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='copy',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
