# Generated by Django 3.0.6 on 2020-06-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pemesanan_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
